version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: swoole-http-server 
    ports:
      - '82:9501'
    volumes:
      - './:/var/www/html'
    networks:
      - swoole-app
networks:
  swoole-app:
    driver: bridge
